EveryQuestData["Miscellaneous"] = {
[-365] = {
	{ ["id"] = 8848,["n"] = "Fifteen Signets for War Supplies",["l"] = 39,["r"] = 30,["s"] = 0,},
	{ ["id"] = 8853,["n"] = "Fifteen Signets for War Supplies",["l"] = 39,["r"] = 30,["s"] = 0,},
	{ ["id"] = 8846,["n"] = "Five Signets for War Supplies",["l"] = 19,["r"] = 10,["s"] = 1,},
	{ ["id"] = 8851,["n"] = "Five Signets for War Supplies",["l"] = 19,["r"] = 10,["s"] = 0,},
	{ ["id"] = 8852,["n"] = "Ten Signets for War Supplies",["l"] = 29,["r"] = 20,["s"] = 0,},
	{ ["id"] = 8847,["n"] = "Ten Signets for War Supplies",["l"] = 29,["r"] = 20,["s"] = 0,},
	{ ["id"] = 8509,["n"] = "The Alliance Needs Arthas' Tears!",["l"] = 60,["r"] = 1,["s"] = 1,},
	{ ["id"] = 8492,["n"] = "The Alliance Needs Copper Bars!",["l"] = 60,["r"] = 1,["s"] = 1,},
	{ ["id"] = 8494,["n"] = "The Alliance Needs Iron Bars!",["l"] = 60,["r"] = 1,["s"] = 1,},
	{ ["id"] = 8511,["n"] = "The Alliance Needs Light Leather!",["l"] = 60,["r"] = 1,["s"] = 1,},
	{ ["id"] = 8517,["n"] = "The Alliance Needs Linen Bandages!",["l"] = 60,["r"] = 1,["s"] = 1,},
	{ ["id"] = 8513,["n"] = "The Alliance Needs Medium Leather!",["l"] = 60,["r"] = 1,["s"] = 1,},
	{ ["id"] = 8510,["n"] = "The Alliance Needs More Arthas' Tears!",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 8493,["n"] = "The Alliance Needs More Copper Bars!",["l"] = 60,["r"] = 1,["s"] = 1,},
	{ ["id"] = 8495,["n"] = "The Alliance Needs More Iron Bars!",["l"] = 60,["r"] = 1,["s"] = 1,},
	{ ["id"] = 8512,["n"] = "The Alliance Needs More Light Leather!",["l"] = 60,["r"] = 1,["s"] = 1,},
	{ ["id"] = 8518,["n"] = "The Alliance Needs More Linen Bandages!",["l"] = 60,["r"] = 1,["s"] = 1,},
	{ ["id"] = 8514,["n"] = "The Alliance Needs More Medium Leather!",["l"] = 60,["r"] = 1,["s"] = 1,},
	{ ["id"] = 8506,["n"] = "The Alliance Needs More Purple Lotus!",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 8525,["n"] = "The Alliance Needs More Rainbow Fin Albacore!",["l"] = 60,["r"] = 1,["s"] = 1,},
	{ ["id"] = 8527,["n"] = "The Alliance Needs More Roast Raptor!",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 8523,["n"] = "The Alliance Needs More Runecloth Bandages!",["l"] = 60,["r"] = 1,["s"] = 1,},
	{ ["id"] = 8521,["n"] = "The Alliance Needs More Silk Bandages!",["l"] = 60,["r"] = 1,["s"] = 1,},
	{ ["id"] = 8529,["n"] = "The Alliance Needs More Spotted Yellowtail!",["l"] = 60,["r"] = 1,["s"] = 1,},
	{ ["id"] = 8504,["n"] = "The Alliance Needs More Stranglekelp!",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 8516,["n"] = "The Alliance Needs More Thick Leather!",["l"] = 60,["r"] = 1,["s"] = 1,},
	{ ["id"] = 8500,["n"] = "The Alliance Needs More Thorium Bars!",["l"] = 60,["r"] = 1,["s"] = 1,},
	{ ["id"] = 8505,["n"] = "The Alliance Needs Purple Lotus!",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 8524,["n"] = "The Alliance Needs Rainbow Fin Albacore!",["l"] = 60,["r"] = 1,["s"] = 1,},
	{ ["id"] = 8526,["n"] = "The Alliance Needs Roast Raptor!",["l"] = 60,["r"] = 1,["s"] = 1,},
	{ ["id"] = 8522,["n"] = "The Alliance Needs Runecloth Bandages!",["l"] = 60,["r"] = 1,["s"] = 1,},
	{ ["id"] = 8520,["n"] = "The Alliance Needs Silk Bandages!",["l"] = 60,["r"] = 1,["s"] = 1,},
	{ ["id"] = 8528,["n"] = "The Alliance Needs Spotted Yellowtail!",["l"] = 60,["r"] = 1,["s"] = 1,},
	{ ["id"] = 8503,["n"] = "The Alliance Needs Stranglekelp!",["l"] = 60,["r"] = 1,["s"] = 1,},
	{ ["id"] = 8515,["n"] = "The Alliance Needs Thick Leather!",["l"] = 60,["r"] = 1,["s"] = 1,},
	{ ["id"] = 8499,["n"] = "The Alliance Needs Thorium Bars!",["l"] = 60,["r"] = 1,["s"] = 1,},
	{ ["id"] = 8795,["n"] = "The Alliance Needs Your Help!",["l"] = 60,["r"] = 46,["s"] = 0,},
	{ ["id"] = 8796,["n"] = "The Alliance Needs Your Help!",["l"] = 60,["r"] = 37,["s"] = 0,},
	{ ["id"] = 8797,["n"] = "The Alliance Needs Your Help!",["l"] = 60,["s"] = 0,},
	{ ["id"] = 10501,["n"] = "The Alliance Needs Your Help!",["l"] = 60,["r"] = 10,["s"] = 0,},
	{ ["id"] = 8615,["n"] = "The Horde Needs Baked Salmon!",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 8532,["n"] = "The Horde Needs Copper Bars!",["l"] = 60,["r"] = 1,["s"] = 2,},
	{ ["id"] = 8580,["n"] = "The Horde Needs Firebloom!",["l"] = 60,["r"] = 1,["s"] = 2,},
	{ ["id"] = 8588,["n"] = "The Horde Needs Heavy Leather!",["l"] = 60,["r"] = 1,["s"] = 2,},
	{ ["id"] = 8611,["n"] = "The Horde Needs Lean Wolf Steaks!",["l"] = 60,["r"] = 1,["s"] = 2,},
	{ ["id"] = 8607,["n"] = "The Horde Needs Mageweave Bandages!",["l"] = 60,["r"] = 1,["s"] = 2,},
	{ ["id"] = 8545,["n"] = "The Horde Needs Mithril Bars!",["l"] = 60,["r"] = 1,["s"] = 2,},
	{ ["id"] = 8616,["n"] = "The Horde Needs More Baked Salmon!",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 8533,["n"] = "The Horde Needs More Copper Bars!",["l"] = 60,["r"] = 1,["s"] = 2,},
	{ ["id"] = 8581,["n"] = "The Horde Needs More Firebloom!",["l"] = 60,["r"] = 1,["s"] = 2,},
	{ ["id"] = 8589,["n"] = "The Horde Needs More Heavy Leather!",["l"] = 60,["r"] = 1,["s"] = 2,},
	{ ["id"] = 8612,["n"] = "The Horde Needs More Lean Wolf Steaks!",["l"] = 60,["r"] = 1,["s"] = 2,},
	{ ["id"] = 8608,["n"] = "The Horde Needs More Mageweave Bandages!",["l"] = 60,["r"] = 1,["s"] = 2,},
	{ ["id"] = 8546,["n"] = "The Horde Needs More Mithril Bars!",["l"] = 60,["r"] = 1,["s"] = 2,},
	{ ["id"] = 8550,["n"] = "The Horde Needs More Peacebloom!",["l"] = 60,["r"] = 1,["s"] = 2,},
	{ ["id"] = 8583,["n"] = "The Horde Needs More Purple Lotus!",["l"] = 60,["r"] = 1,["s"] = 2,},
	{ ["id"] = 8601,["n"] = "The Horde Needs More Rugged Leather!",["l"] = 60,["r"] = 1,["s"] = 2,},
	{ ["id"] = 8610,["n"] = "The Horde Needs More Runecloth Bandages!",["l"] = 60,["r"] = 1,["s"] = 2,},
	{ ["id"] = 8614,["n"] = "The Horde Needs More Spotted Yellowtail!",["l"] = 60,["r"] = 1,["s"] = 2,},
	{ ["id"] = 8591,["n"] = "The Horde Needs More Thick Leather!",["l"] = 60,["r"] = 1,["s"] = 2,},
	{ ["id"] = 8543,["n"] = "The Horde Needs More Tin Bars!",["l"] = 60,["r"] = 1,["s"] = 2,},
	{ ["id"] = 8605,["n"] = "The Horde Needs More Wool Bandages!",["l"] = 60,["r"] = 1,["s"] = 2,},
	{ ["id"] = 8549,["n"] = "The Horde Needs Peacebloom!",["l"] = 60,["r"] = 1,["s"] = 2,},
	{ ["id"] = 8582,["n"] = "The Horde Needs Purple Lotus!",["l"] = 60,["r"] = 1,["s"] = 2,},
	{ ["id"] = 8600,["n"] = "The Horde Needs Rugged Leather!",["l"] = 60,["r"] = 1,["s"] = 2,},
	{ ["id"] = 8609,["n"] = "The Horde Needs Runecloth Bandages!",["l"] = 60,["r"] = 1,["s"] = 2,},
	{ ["id"] = 8613,["n"] = "The Horde Needs Spotted Yellowtail!",["l"] = 60,["r"] = 1,["s"] = 2,},
	{ ["id"] = 8590,["n"] = "The Horde Needs Thick Leather!",["l"] = 60,["r"] = 1,["s"] = 2,},
	{ ["id"] = 8542,["n"] = "The Horde Needs Tin Bars!",["l"] = 60,["r"] = 1,["s"] = 2,},
	{ ["id"] = 8604,["n"] = "The Horde Needs Wool Bandages!",["l"] = 60,["r"] = 1,["s"] = 2,},
	{ ["id"] = 8794,["n"] = "The Horde Needs Your Help!",["l"] = 60,["r"] = 30,["s"] = 2,},
	{ ["id"] = 8793,["n"] = "The Horde Needs Your Help!",["l"] = 60,["r"] = 9,["s"] = 2,},
	{ ["id"] = 8792,["n"] = "The Horde Needs Your Help!",["l"] = 60,["r"] = 59,["s"] = 2,},
	{ ["id"] = 10500,["n"] = "The Horde Needs Your Help!",["l"] = 60,["r"] = 13,["s"] = 0,},
	{ ["id"] = 8850,["n"] = "Thirty Signets for War Supplies",["l"] = 60,["r"] = 50,["s"] = 0,},
	{ ["id"] = 8855,["n"] = "Thirty Signets for War Supplies",["l"] = 60,["r"] = 50,["s"] = 0,},
	{ ["id"] = 8849,["n"] = "Twenty Signets for War Supplies",["l"] = 49,["r"] = 40,["s"] = 0,},
	{ ["id"] = 8854,["n"] = "Twenty Signets for War Supplies",["l"] = 49,["r"] = 40,["s"] = 0,},
},
[-1] = {
	{ ["id"] = 8446,["n"] = "Shrouded in Nightmare",["l"] = 60,["r"] = 60,["s"] = 3,},
	{ ["id"] = 8447,["n"] = "Waking Legends",["l"] = 60,["r"] = 60,["s"] = 3,},
},
[-344] = {
	{ ["id"] = 7785,["n"] = "Examine the Vessel",["l"] = 60,["r"] = 60,["s"] = 3,},
	{ ["id"] = 7787,["n"] = "Rise, Thunderfury!",["l"] = 60,["r"] = 60,["s"] = 3,},
	{ ["id"] = 9251,["n"] = "Atiesh, the Befouled Greatstaff",["l"] = 60,["r"] = 60,["s"] = 3,["t"] = 62,},
	{ ["id"] = 9250,["n"] = "Frame of Atiesh",["l"] = 60,["r"] = 60,["s"] = 3,["t"] = 62,},
	{ ["id"] = 7786,["n"] = "Thunderaan the Windseeker",["l"] = 60,["r"] = 60,["s"] = 3,["t"] = 62,},
	{ ["id"] = 9257,["n"] = "Atiesh, Greatstaff of the Guardian",["l"] = 60,["r"] = 60,["s"] = 0,["t"] = 81,},
	{ ["id"] = 9269,["n"] = "Atiesh, Greatstaff of the Guardian",["l"] = 60,["r"] = 60,["s"] = 0,["t"] = 81,},
	{ ["id"] = 9270,["n"] = "Atiesh, Greatstaff of the Guardian",["l"] = 60,["r"] = 60,["s"] = 0,["t"] = 81,},
	{ ["id"] = 9271,["n"] = "Atiesh, Greatstaff of the Guardian",["l"] = 60,["r"] = 60,["s"] = 0,["t"] = 81,},
},
[-367] = {
	{ ["id"] = 8811,["n"] = "One Commendation Signet",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 8838,["n"] = "One Commendation Signet",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 8840,["n"] = "One Commendation Signet",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 8842,["n"] = "One Commendation Signet",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 8844,["n"] = "One Commendation Signet",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 10699,["n"] = "One Commendation Signet",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 10697,["n"] = "One Commendation Signet",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 10695,["n"] = "One Commendation Signet",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 10693,["n"] = "One Commendation Signet",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 8836,["n"] = "One Commendation Signet",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 8834,["n"] = "One Commendation Signet",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 8832,["n"] = "One Commendation Signet",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 8812,["n"] = "One Commendation Signet",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 8813,["n"] = "One Commendation Signet",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 8814,["n"] = "One Commendation Signet",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 8815,["n"] = "One Commendation Signet",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 8818,["n"] = "One Commendation Signet",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 8816,["n"] = "One Commendation Signet",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 8817,["n"] = "One Commendation Signet",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 8830,["n"] = "One Commendation Signet",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 8841,["n"] = "Ten Commendation Signets",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 8843,["n"] = "Ten Commendation Signets",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 8845,["n"] = "Ten Commendation Signets",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 10698,["n"] = "Ten Commendation Signets",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 10694,["n"] = "Ten Commendation Signets",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 10696,["n"] = "Ten Commendation Signets",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 8839,["n"] = "Ten Commendation Signets",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 8837,["n"] = "Ten Commendation Signets",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 8835,["n"] = "Ten Commendation Signets",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 8819,["n"] = "Ten Commendation Signets",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 8820,["n"] = "Ten Commendation Signets",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 8821,["n"] = "Ten Commendation Signets",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 8822,["n"] = "Ten Commendation Signets",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 8823,["n"] = "Ten Commendation Signets",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 8824,["n"] = "Ten Commendation Signets",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 8825,["n"] = "Ten Commendation Signets",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 8826,["n"] = "Ten Commendation Signets",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 8831,["n"] = "Ten Commendation Signets",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 8833,["n"] = "Ten Commendation Signets",["l"] = 60,["r"] = 1,["s"] = 0,},
	{ ["id"] = 10700,["n"] = "Ten Commendation Signets",["l"] = 60,["r"] = 1,["s"] = 0,},
},
[-368] = {
	{ ["id"] = 9094,["n"] = "Argent Dawn Gloves",["r"] = 50,["s"] = 0,},
	{ ["id"] = 9333,["n"] = "Argent Dawn Gloves",["r"] = 50,["s"] = 0,},
	{ ["id"] = 9318,["n"] = "Blessed Wizard Oil",["r"] = 50,["s"] = 0,},
	{ ["id"] = 9334,["n"] = "Blessed Wizard Oil",["r"] = 50,["s"] = 0,},
	{ ["id"] = 9317,["n"] = "Consecrated Sharpening Stones",["r"] = 50,["s"] = 0,},
	{ ["id"] = 9335,["n"] = "Consecrated Sharpening Stones",["r"] = 50,["s"] = 0,},
	{ ["id"] = 9292,["n"] = "Cracked Necrotic Crystal",["s"] = 0,},
	{ ["id"] = 9304,["n"] = "Document from the Front",["r"] = 45,["s"] = 0,},
	{ ["id"] = 9301,["n"] = "Envelope from the Front",["r"] = 45,["s"] = 0,},
	{ ["id"] = 9310,["n"] = "Faint Necrotic Crystal",["s"] = 0,},
	{ ["id"] = 9262,["n"] = "Investigate the Scourge of Darnassus",["l"] = 10,["r"] = 1,["s"] = 0,},
	{ ["id"] = 9261,["n"] = "Investigate the Scourge of Ironforge",["l"] = 10,["r"] = 1,["s"] = 0,},
	{ ["id"] = 9263,["n"] = "Investigate the Scourge of Orgrimmar",["l"] = 10,["r"] = 1,["s"] = 0,},
	{ ["id"] = 9260,["n"] = "Investigate the Scourge of Stormwind",["l"] = 6,["r"] = 1,["s"] = 0,},
	{ ["id"] = 9265,["n"] = "Investigate the Scourge of the Undercity",["l"] = 8,["r"] = 1,["s"] = 0,},
	{ ["id"] = 9264,["n"] = "Investigate the Scourge of Thunder Bluff",["l"] = 10,["r"] = 1,["s"] = 0,},
	{ ["id"] = 9295,["n"] = "Letter from the Front",["r"] = 45,["s"] = 0,},
	{ ["id"] = 9154,["n"] = "Light's Hope Chapel",["r"] = 50,["s"] = 0,},
	{ ["id"] = 9321,["n"] = "Major Healing Potion",["r"] = 50,["s"] = 0,},
	{ ["id"] = 9336,["n"] = "Major Healing Potion",["r"] = 50,["s"] = 0,},
	{ ["id"] = 9320,["n"] = "Major Mana Potion",["r"] = 50,["s"] = 0,},
	{ ["id"] = 9337,["n"] = "Major Mana Potion",["r"] = 50,["s"] = 0,},
	{ ["id"] = 9302,["n"] = "Missive from the Front",["r"] = 45,["s"] = 0,},
	{ ["id"] = 9299,["n"] = "Note from the Front",["r"] = 45,["s"] = 0,},
	{ ["id"] = 9300,["n"] = "Page from the Front",["r"] = 45,["s"] = 0,},
	{ ["id"] = 9341,["n"] = "Tabard of the Argent Dawn",["r"] = 50,["s"] = 0,},
	{ ["id"] = 9343,["n"] = "Tabard of the Argent Dawn",["r"] = 50,["s"] = 0,},
	{ ["id"] = 9247,["n"] = "The Keeper's Call",["r"] = 60,["s"] = 0,},
	{ ["id"] = 9153,["n"] = "Under the Shadow",["r"] = 50,["s"] = 0,},
	{ ["id"] = 9085,["n"] = "Shadows of Doom",["r"] = 50,["s"] = 0,["t"] = 1,},
},
[-22] = {
	{ ["id"] = 12410,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12382,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12383,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12384,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12385,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12386,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12387,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12388,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12389,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12381,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12380,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12371,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12373,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12374,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12375,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12376,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12377,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12378,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12379,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12390,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12391,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12402,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12403,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12404,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12405,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12406,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12407,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12408,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12409,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12401,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12400,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12392,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12393,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12394,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12395,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12396,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12397,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12398,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12399,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12370,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12369,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12341,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12342,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12343,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12344,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12345,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12346,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12347,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12348,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12340,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12339,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12331,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12332,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12333,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12334,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12335,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12336,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12337,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12338,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12349,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12350,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12361,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12362,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12363,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12364,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12365,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12366,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12367,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12368,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12360,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12359,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12351,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12352,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12353,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12354,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12355,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12356,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12357,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12358,["n"] = "Candy Bucket",["s"] = 0,},
	{ ["id"] = 12286,["n"] = "Candy Bucket",["s"] = 0,},
},
}