local L = AceLibrary("AceLocale-2.2"):new("EveryQuest")
L:RegisterTranslations("enUS", function() return{
	["Change Status"] = true,
	["Turned In"] = true,
	["Completed"] = true,
	["In Progress"] = true,
	["Abandoned"] = true,
	["Failed"] = true,
	["Close"] = true,
	
	["EveryQuest Log"] = true,
	["EveryQuest"] = true,
	["Toggle Frame"] = true,
	
	["-- Select --"] = true,
	["Loading "] = true,
	["Could not load "] = true,
	["Failed or Abandoned"] = true,
	
	["Failed: "] = true,
	["Abandoned: "] = true,
	["Completed: "] = true,
	["Status: "] = true,
	
	[" days "] = true,
	[" day "] = true,
	[" hr "] = true,
	["ago"] = true,
	[" min "] = true,
	[" minutes ago"] = true,
	["1 minute ago"] = true,
	[" seconds ago"] = true,
	[" second ago"] = true,
	[" Quest Data"] = true,
	
	["Requires LOD Module: "] = true,
	["Missing LOD Module: "] = true,
	["G"] = true,
	["Group"] = true,
	["R"] = true,
	["Raid"] = true,
	["H"] = true,
	["Heroic"] = true,
	["D"] = true,
	["Dungeon"] = true,
	["P"] = true,
	["PvP"] = true,
	["Y"] = true,
	["Daily"] = true,
	["Times"] = true,
} end )