#!/usr/bin/env bash

set -euo pipefail

: "${CI_API_V4_URL:?CI_API_V4_URL is required}"
: "${CI_JOB_TOKEN:?CI_JOB_TOKEN is required}"
: "${CI_PROJECT_ID:?CI_PROJECT_ID is required}"

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="${PACKAGE_REPO_ROOT:-$(cd "$script_dir/.." && pwd)}"
repo_root="$(cd "$repo_root" && pwd)"
tag="${1:?release tag is required}"
package_name="${GITLAB_PACKAGE_NAME:-everyquest-tbc-anniversary}"

urlencode() {
  jq -rn --arg value "$1" '$value | @uri'
}

gitlab_api() {
  curl --fail --silent --show-error --location --retry 3 \
    --header "JOB-TOKEN: ${CI_JOB_TOKEN}" \
    "$@"
}

PACKAGE_REPO_ROOT="$repo_root" "$script_dir/package-release.sh" "$tag"
# release.env is generated by package-release.sh above.
# shellcheck disable=SC1091
source "$repo_root/dist/release.env"

encoded_tag="$(urlencode "$RELEASE_TAG")"
encoded_version="$(urlencode "$RELEASE_VERSION")"
release_url="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/releases/${encoded_tag}"

for asset_name in "$RELEASE_ASSET" "${RELEASE_ASSET}.sha256"; do
  encoded_asset_name="$(urlencode "$asset_name")"
  asset_path="$repo_root/dist/$asset_name"
  existing_asset_path="$repo_root/dist/${asset_name}.existing"
  package_url="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${package_name}/${encoded_version}/${encoded_asset_name}"

  echo "Publishing GitLab package asset $asset_name"
  if gitlab_api "$package_url" --output "$existing_asset_path" 2>/dev/null &&
      cmp --silent "$asset_path" "$existing_asset_path"; then
    echo "Package asset is already current: $asset_name"
  else
    gitlab_api \
      --request PUT \
      --upload-file "$asset_path" \
      "$package_url" \
      --output /dev/null
  fi
done

description="$(cat "$repo_root/dist/release-notes.md")"
if gitlab_api "$release_url" --output "$repo_root/dist/gitlab-release.json" 2>/dev/null; then
  jq -n \
    --arg name "$RELEASE_VERSION" \
    --arg description "$description" \
    '{name: $name, description: $description}' \
    > "$repo_root/dist/gitlab-release-payload.json"

  gitlab_api \
    --request PUT \
    --header 'Content-Type: application/json' \
    --data @"$repo_root/dist/gitlab-release-payload.json" \
    "$release_url" \
    --output /dev/null
else
  jq -n \
    --arg name "$RELEASE_VERSION" \
    --arg tag_name "$RELEASE_TAG" \
    --arg ref "$RELEASE_TAG" \
    --arg description "$description" \
    '{name: $name, tag_name: $tag_name, ref: $ref, description: $description}' \
    > "$repo_root/dist/gitlab-release-payload.json"

  gitlab_api \
    --request POST \
    --header 'Content-Type: application/json' \
    --data @"$repo_root/dist/gitlab-release-payload.json" \
    "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/releases" \
    --output /dev/null
fi

links_url="${release_url}/assets/links"
for asset_name in "$RELEASE_ASSET" "${RELEASE_ASSET}.sha256"; do
  encoded_asset_name="$(urlencode "$asset_name")"
  package_url="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${package_name}/${encoded_version}/${encoded_asset_name}"

  gitlab_api "$links_url" --output "$repo_root/dist/gitlab-release-links.json"
  link_id="$(
    jq -r --arg name "$asset_name" \
      '.[] | select(.name == $name) | .id' \
      "$repo_root/dist/gitlab-release-links.json" |
    head -n 1
  )"

  if [[ -n "$link_id" ]]; then
    gitlab_api \
      --request PUT \
      --data-urlencode "name=${asset_name}" \
      --data-urlencode "url=${package_url}" \
      --data-urlencode 'link_type=package' \
      "${links_url}/${link_id}" \
      --output /dev/null
  else
    gitlab_api \
      --request POST \
      --data-urlencode "name=${asset_name}" \
      --data-urlencode "url=${package_url}" \
      --data-urlencode 'link_type=package' \
      "$links_url" \
      --output /dev/null
  fi
done

echo "GitLab release $RELEASE_TAG is published"
