EveryQuestData["Seasonal"] = {
[-370] = {
	{ ["id"] = 11407,["n"] = "Bark for Drohn's Distillery!",["l"] = 70,["r"] = 8,["s"] = 2,["d"] = 1,},
	{ ["id"] = 11408,["n"] = "Bark for T'chali's Voodoo Brewery!",["l"] = 70,["r"] = 59,["s"] = 2,["d"] = 1,},
	{ ["id"] = 11293,["n"] = "Bark for the Barleybrews!",["l"] = 70,["r"] = 1,["s"] = 1,["d"] = 1,},
	{ ["id"] = 11294,["n"] = "Bark for the Thunderbrews!",["l"] = 70,["r"] = 1,["s"] = 1,["d"] = 1,},
	{ ["id"] = 12062,["n"] = "Insult Coren Direbrew",["l"] = 70,["s"] = 0,["d"] = 1,["t"] = 81,},
	{ ["id"] = 12420,["n"] = "Brew of the Month Club",["s"] = 0,},
	{ ["id"] = 12421,["n"] = "Brew of the Month Club",["s"] = 0,},
	{ ["id"] = 12306,["n"] = "Brew of the Month Club",["s"] = 0,},
	{ ["id"] = 11419,["n"] = "Brewfest Riding Rams",["r"] = 40,["s"] = 2,},
	{ ["id"] = 11400,["n"] = "Brewfest Riding Rams",["r"] = 40,["s"] = 1,},
	{ ["id"] = 11441,["n"] = "Brewfest!",["r"] = 1,["s"] = 1,},
	{ ["id"] = 11446,["n"] = "Brewfest!",["r"] = 1,["s"] = 2,},
	{ ["id"] = 11117,["n"] = "Catch the Wild Wolpertinger!",["r"] = 1,["s"] = 1,},
	{ ["id"] = 11431,["n"] = "Catch the Wild Wolpertinger!",["r"] = 1,["s"] = 2,},
	{ ["id"] = 11321,["n"] = "Did Someone Say \"Souvenir?\"",["r"] = 1,["s"] = 1,},
	{ ["id"] = 11413,["n"] = "Did Someone Say \"Souvenir?\"",["r"] = 1,["s"] = 2,},
	{ ["id"] = 12492,["n"] = "Direbrew's Dire Brew",["s"] = 0,},
	{ ["id"] = 12491,["n"] = "Direbrew's Dire Brew",["s"] = 0,},
	{ ["id"] = 11318,["n"] = "Now This is Ram Racing... Almost.",["l"] = 70,["r"] = 1,["s"] = 1,},
	{ ["id"] = 11409,["n"] = "Now This is Ram Racing... Almost.",["l"] = 70,["r"] = 4,["s"] = 2,},
	{ ["id"] = 11118,["n"] = "Pink Elekks On Parade",["r"] = 1,["s"] = 1,},
	{ ["id"] = 11120,["n"] = "Pink Elekks On Parade",["r"] = 1,["s"] = 2,},
	{ ["id"] = 12318,["n"] = "Save Brewfest!",["s"] = 0,},
	{ ["id"] = 12194,["n"] = "Say, There Wouldn't Happen to be a Souvenir This Year, Would There?",["s"] = 0,},
	{ ["id"] = 12193,["n"] = "Say, There Wouldn't Happen to be a Souvenir This Year, Would There?",["s"] = 0,},
	{ ["id"] = 11487,["n"] = "The Best of Brews",["r"] = 1,["s"] = 2,},
	{ ["id"] = 11486,["n"] = "The Best of Brews",["l"] = 70,["r"] = 1,["s"] = 1,},
	{ ["id"] = 11122,["n"] = "There and Back Again",["l"] = 70,["r"] = 1,["s"] = 1,},
	{ ["id"] = 11412,["n"] = "There and Back Again",["l"] = 70,["r"] = 4,["s"] = 2,},
	{ ["id"] = 11454,["n"] = "Seek the Saboteurs",["l"] = 52,["r"] = 48,["s"] = 3,["t"] = 81,},
},
[-1002] = {
	{ ["id"] = 10952,["n"] = "A Trip to the Dark Portal",["r"] = 60,["s"] = 1,},
	{ ["id"] = 10951,["n"] = "A Trip to the Dark Portal",["r"] = 60,["s"] = 2,},
	{ ["id"] = 171,["n"] = "A Warden of the Alliance",["r"] = 11,["s"] = 1,},
	{ ["id"] = 5502,["n"] = "A Warden of the Horde",["r"] = 10,["s"] = 2,},
	{ ["id"] = 10950,["n"] = "Auchindoun and the Ring of Observance",["r"] = 60,["s"] = 1,},
	{ ["id"] = 10967,["n"] = "Back to the Orphanage",["r"] = 60,["s"] = 2,},
	{ ["id"] = 10966,["n"] = "Back to the Orphanage",["r"] = 60,["s"] = 1,},
	{ ["id"] = 925,["n"] = "Cairne's Hoofprint",["r"] = 10,["s"] = 2,},
	{ ["id"] = 10968,["n"] = "Call on the Farseer",["r"] = 60,["s"] = 1,},
	{ ["id"] = 10943,["n"] = "Children's Week",["r"] = 60,["s"] = 1,},
	{ ["id"] = 10942,["n"] = "Children's Week",["r"] = 60,["s"] = 2,},
	{ ["id"] = 172,["n"] = "Children's Week",["r"] = 10,["s"] = 2,},
	{ ["id"] = 1468,["n"] = "Children's Week",["r"] = 10,["s"] = 1,},
	{ ["id"] = 910,["n"] = "Down at the Docks",["r"] = 10,["s"] = 2,},
	{ ["id"] = 911,["n"] = "Gateway to the Frontier",["r"] = 10,["s"] = 2,},
	{ ["id"] = 10945,["n"] = "Hch'uu and the Mushroom People",["r"] = 60,["s"] = 2,},
	{ ["id"] = 558,["n"] = "Jaina's Autograph",["r"] = 11,["s"] = 1,},
	{ ["id"] = 10954,["n"] = "Jheel is at Aeris Landing!",["r"] = 60,["s"] = 1,},
	{ ["id"] = 1800,["n"] = "Lordaeron Throne Room",["r"] = 10,["s"] = 2,},
	{ ["id"] = 11975,["n"] = "Now, When I Grow Up...",["r"] = 60,["s"] = 2,},
	{ ["id"] = 1687,["n"] = "Spooky Lighthouse",["r"] = 10,["s"] = 1,},
	{ ["id"] = 1479,["n"] = "The Bough of the Eternals",["r"] = 10,["s"] = 1,},
	{ ["id"] = 10956,["n"] = "The Seat of the Naaru",["r"] = 60,["s"] = 1,},
	{ ["id"] = 1558,["n"] = "The Stonewrought Dam",["r"] = 10,["s"] = 1,},
	{ ["id"] = 10963,["n"] = "Time to Visit the Caverns",["r"] = 60,["s"] = 2,},
	{ ["id"] = 10962,["n"] = "Time to Visit the Caverns",["r"] = 60,["s"] = 1,},
	{ ["id"] = 10953,["n"] = "Visit the Throne of the Elements",["r"] = 60,["s"] = 2,},
	{ ["id"] = 10960,["n"] = "When I Grow Up...",["r"] = 60,["s"] = 2,},
	{ ["id"] = 4822,["n"] = "You Scream, I Scream...",["r"] = 11,["s"] = 0,},
	{ ["id"] = 915,["n"] = "You Scream, I Scream...",["r"] = 10,["s"] = 0,},
},
[-364] = {
	{ ["id"] = 7935,["n"] = "10 Tickets - Last Month's Mutton",["r"] = 25,["s"] = 3,},
	{ ["id"] = 7932,["n"] = "12 Tickets - Lesser Darkmoon Prize",["r"] = 30,["s"] = 3,},
	{ ["id"] = 7981,["n"] = "1200 Tickets - Amulet of the Darkmoon",["r"] = 55,["s"] = 3,},
	{ ["id"] = 7940,["n"] = "1200 Tickets - Orb of the Darkmoon",["r"] = 55,["s"] = 3,},
	{ ["id"] = 9249,["n"] = "40 Tickets - \"Schematic\": Steam Tonk Controller",["r"] = 45,["s"] = 3,},
	{ ["id"] = 7933,["n"] = "40 Tickets - Greater Darkmoon Prize",["r"] = 45,["s"] = 3,},
	{ ["id"] = 7930,["n"] = "5 Tickets - Darkmoon Flower",["r"] = 6,["s"] = 3,},
	{ ["id"] = 7931,["n"] = "5 Tickets - Minor Darkmoon Prize",["r"] = 15,["s"] = 3,},
	{ ["id"] = 7934,["n"] = "50 Tickets - Darkmoon Storage Box",["r"] = 6,["s"] = 3,},
	{ ["id"] = 7936,["n"] = "50 Tickets - Last Year's Mutton",["r"] = 45,["s"] = 3,},
	{ ["id"] = 7885,["n"] = "Armor Kits",["r"] = 40,["s"] = 3,},
	{ ["id"] = 7892,["n"] = "Big Black Mace",["r"] = 30,["s"] = 3,},
	{ ["id"] = 7881,["n"] = "Carnival Boots",["r"] = 1,["s"] = 3,},
	{ ["id"] = 7882,["n"] = "Carnival Jerkins",["r"] = 10,["s"] = 3,},
	{ ["id"] = 7889,["n"] = "Coarse Weightstone",["r"] = 1,["s"] = 3,},
	{ ["id"] = 7894,["n"] = "Copper Modulator",["r"] = 1,["s"] = 3,},
	{ ["id"] = 7884,["n"] = "Crocolisk Boy and the Bearded Murloc",["r"] = 30,["s"] = 3,},
	{ ["id"] = 7907,["n"] = "Darkmoon Beast Deck",["r"] = 11,["s"] = 3,},
	{ ["id"] = 10938,["n"] = "Darkmoon Blessings Deck",["l"] = 70,["r"] = 64,["s"] = 3,},
	{ ["id"] = 7929,["n"] = "Darkmoon Elementals Deck",["r"] = 1,["s"] = 3,},
	{ ["id"] = 10940,["n"] = "Darkmoon Furies Deck",["l"] = 70,["r"] = 67,["s"] = 3,},
	{ ["id"] = 10941,["n"] = "Darkmoon Lunacy Deck",["l"] = 70,["r"] = 67,["s"] = 3,},
	{ ["id"] = 7927,["n"] = "Darkmoon Portals Deck",["r"] = 29,["s"] = 3,},
	{ ["id"] = 10939,["n"] = "Darkmoon Storms Deck",["l"] = 70,["r"] = 63,["s"] = 3,},
	{ ["id"] = 7928,["n"] = "Darkmoon Warlords Deck",["r"] = 1,["s"] = 3,},
	{ ["id"] = 7903,["n"] = "Evil Bat Eyes",["r"] = 40,["s"] = 3,},
	{ ["id"] = 8222,["n"] = "Glowing Scorpid Blood",["r"] = 40,["s"] = 3,},
	{ ["id"] = 7896,["n"] = "Green Fireworks",["r"] = 20,["s"] = 3,},
	{ ["id"] = 7891,["n"] = "Green Iron Bracers",["r"] = 20,["s"] = 3,},
	{ ["id"] = 7890,["n"] = "Heavy Grinding Stone",["r"] = 10,["s"] = 3,},
	{ ["id"] = 7897,["n"] = "Mechanical Repair Kits",["r"] = 30,["s"] = 3,},
	{ ["id"] = 7941,["n"] = "More Armor Kits",["r"] = 40,["s"] = 3,},
	{ ["id"] = 7943,["n"] = "More Bat Eyes",["r"] = 40,["s"] = 3,},
	{ ["id"] = 7939,["n"] = "More Dense Grinding Stones",["r"] = 40,["s"] = 3,},
	{ ["id"] = 8223,["n"] = "More Glowing Scorpid Blood",["r"] = 40,["s"] = 3,},
	{ ["id"] = 7942,["n"] = "More Thorium Widgets",["r"] = 40,["s"] = 3,},
	{ ["id"] = 7893,["n"] = "Rituals of Strength",["r"] = 40,["s"] = 3,},
	{ ["id"] = 7899,["n"] = "Small Furry Paws",["r"] = 1,["s"] = 3,},
	{ ["id"] = 7901,["n"] = "Soft Bushy Tails",["r"] = 20,["s"] = 3,},
	{ ["id"] = 7946,["n"] = "Spawn of Jubjub",["r"] = 10,["s"] = 3,},
	{ ["id"] = 7883,["n"] = "The World's Largest Gnome!",["r"] = 20,["s"] = 3,},
	{ ["id"] = 7898,["n"] = "Thorium Widget",["r"] = 40,["s"] = 3,},
	{ ["id"] = 7900,["n"] = "Torn Bear Pelts",["r"] = 10,["s"] = 3,},
	{ ["id"] = 7902,["n"] = "Vibrant Plumes",["r"] = 30,["s"] = 3,},
	{ ["id"] = 7895,["n"] = "Whirring Bronze Gizmo",["r"] = 10,["s"] = 3,},
	{ ["id"] = 7945,["n"] = "Your Fortune Awaits You...",["r"] = 10,["s"] = 3,},
	{ ["id"] = 7938,["n"] = "Your Fortune Awaits You...",["r"] = 10,["s"] = 3,},
	{ ["id"] = 7937,["n"] = "Your Fortune Awaits You...",["r"] = 10,["s"] = 3,},
	{ ["id"] = 7944,["n"] = "Your Fortune Awaits You...",["r"] = 10,["s"] = 3,},
},
[-1003] = {
	{ ["id"] = 12135,["n"] = "\"Let the Fires Come!\"",["s"] = 0,["d"] = 1,},
	{ ["id"] = 12139,["n"] = "\"Let the Fires Come!\"",["s"] = 0,["d"] = 1,},
	{ ["id"] = 11404,["n"] = "Call the Headless Horseman",["r"] = 65,["s"] = 0,["d"] = 1,},
	{ ["id"] = 12155,["n"] = "Smash the Pumpkin",["s"] = 0,["d"] = 1,},
	{ ["id"] = 12133,["n"] = "Smash the Pumpkin",["s"] = 0,["d"] = 1,},
	{ ["id"] = 11131,["n"] = "Stop the Fires!",["r"] = 1,["s"] = 1,["d"] = 1,},
	{ ["id"] = 11219,["n"] = "Stop the Fires!",["s"] = 2,["d"] = 1,},
	{ ["id"] = 11405,["n"] = "Call the Headless Horseman",["r"] = 65,["s"] = 0,["d"] = 1,["t"] = 81,},
	{ ["id"] = 11401,["n"] = "Call the Headless Horseman",["r"] = 65,["s"] = 0,["d"] = 1,["t"] = 81,},
	{ ["id"] = 11392,["n"] = "Call the Headless Horseman",["l"] = 70,["r"] = 65,["s"] = 0,},
	{ ["id"] = 8353,["n"] = "Chicken Clucking for a Mint",["r"] = 10,["s"] = 1,},
	{ ["id"] = 8354,["n"] = "Chicken Clucking for a Mint",["r"] = 10,["s"] = 2,},
	{ ["id"] = 11356,["n"] = "Costumed Orphan Matron",["l"] = 70,["r"] = 4,["s"] = 1,},
	{ ["id"] = 8360,["n"] = "Dancing for Marzipan",["r"] = 10,["s"] = 2,},
	{ ["id"] = 8357,["n"] = "Dancing for Marzipan",["r"] = 10,["s"] = 1,},
	{ ["id"] = 11439,["n"] = "Fire Brigade Practice",["s"] = 0,},
	{ ["id"] = 11360,["n"] = "Fire Brigade Practice",["r"] = 1,["s"] = 1,},
	{ ["id"] = 11440,["n"] = "Fire Brigade Practice",["s"] = 0,},
	{ ["id"] = 11361,["n"] = "Fire Training",["l"] = 70,["r"] = 1,["s"] = 2,},
	{ ["id"] = 11450,["n"] = "Fire Training",["s"] = 0,},
	{ ["id"] = 11449,["n"] = "Fire Training",["s"] = 0,},
	{ ["id"] = 8359,["n"] = "Flexing for Nougat",["r"] = 10,["s"] = 2,},
	{ ["id"] = 8356,["n"] = "Flexing for Nougat",["r"] = 10,["s"] = 1,},
	{ ["id"] = 11242,["n"] = "Free at Last!",["s"] = 2,},
	{ ["id"] = 11403,["n"] = "Free at Last!",["s"] = 0,},
	{ ["id"] = 8311,["n"] = "Hallow's End Treats for Jesper!",["l"] = 70,["r"] = 10,["s"] = 1,},
	{ ["id"] = 8312,["n"] = "Hallow's End Treats for Spoops!",["r"] = 10,["s"] = 2,},
	{ ["id"] = 8355,["n"] = "Incoming Gumdrop",["r"] = 10,["s"] = 1,},
	{ ["id"] = 8358,["n"] = "Incoming Gumdrop",["r"] = 10,["s"] = 2,},
	{ ["id"] = 11357,["n"] = "Masked Orphan Matron",["l"] = 70,["r"] = 58,["s"] = 2,},
	{ ["id"] = 11135,["n"] = "The Headless Horseman",["l"] = 70,["r"] = 66,["s"] = 0,},
	{ ["id"] = 11220,["n"] = "The Headless Horseman",["l"] = 70,["r"] = 68,["s"] = 0,},
	{ ["id"] = 1658,["n"] = "Crashing the Wickerman Festival",["r"] = 25,["s"] = 1,["t"] = 41,},
	{ ["id"] = 8322,["n"] = "Rotten Eggs",["r"] = 30,["s"] = 2,["t"] = 41,},
	{ ["id"] = 8409,["n"] = "Ruined Kegs",["r"] = 32,["s"] = 2,["t"] = 41,},
	{ ["id"] = 1657,["n"] = "Stinking Up Southshore",["r"] = 25,["s"] = 2,["t"] = 41,},
	{ ["id"] = 8373,["n"] = "The Power of Pine",["r"] = 25,["s"] = 1,["t"] = 41,},
},
[-1005] = {
	{ ["id"] = 8149,["n"] = "Honoring a Hero",["r"] = 30,["s"] = 1,},
	{ ["id"] = 8150,["n"] = "Honoring a Hero",["r"] = 30,["s"] = 2,},
},
[-1004] = {
	{ ["id"] = 9029,["n"] = "A Bubbling Cauldron",["r"] = 1,["s"] = 3,},
	{ ["id"] = 9024,["n"] = "Aristan's Hunch",["r"] = 1,["s"] = 1,},
	{ ["id"] = 8903,["n"] = "Dangerous Love",["r"] = 1,["s"] = 1,},
	{ ["id"] = 8904,["n"] = "Dangerous Love",["r"] = 1,["s"] = 2,},
	{ ["id"] = 8899,["n"] = "Dearest Colara,",["r"] = 1,["s"] = 1,},
	{ ["id"] = 8898,["n"] = "Dearest Colara,",["r"] = 1,["s"] = 1,},
	{ ["id"] = 8897,["n"] = "Dearest Colara,",["r"] = 1,["s"] = 1,},
	{ ["id"] = 8900,["n"] = "Dearest Elenia,",["r"] = 1,["s"] = 2,},
	{ ["id"] = 8901,["n"] = "Dearest Elenia,",["r"] = 1,["s"] = 2,},
	{ ["id"] = 8902,["n"] = "Dearest Elenia,",["r"] = 1,["s"] = 2,},
	{ ["id"] = 8979,["n"] = "Fenstad's Hunch",["r"] = 1,["s"] = 2,},
	{ ["id"] = 8981,["n"] = "Gift Giving",["s"] = 0,},
	{ ["id"] = 8993,["n"] = "Gift Giving",["s"] = 0,},
	{ ["id"] = 9025,["n"] = "Morgan's Discovery",["r"] = 1,["s"] = 1,},
	{ ["id"] = 8984,["n"] = "The Source Revealed",["r"] = 1,["s"] = 2,},
	{ ["id"] = 9028,["n"] = "The Source Revealed",["r"] = 1,["s"] = 1,},
	{ ["id"] = 9027,["n"] = "Tracing the Source",["r"] = 1,["s"] = 1,},
	{ ["id"] = 9026,["n"] = "Tracing the Source",["r"] = 1,["s"] = 1,},
	{ ["id"] = 8983,["n"] = "Tracing the Source",["r"] = 1,["s"] = 2,},
	{ ["id"] = 8982,["n"] = "Tracing the Source",["r"] = 1,["s"] = 2,},
	{ ["id"] = 8980,["n"] = "Zinge's Assessment",["r"] = 1,["s"] = 2,},
},
[-366] = {
	{ ["id"] = 8647,["n"] = "Bellowrage the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8715,["n"] = "Bladeleaf the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8719,["n"] = "Bladesing the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8718,["n"] = "Bladeswift the Elder",["r"] = 1,["s"] = 1,},
	{ ["id"] = 8673,["n"] = "Bloodhoof the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8726,["n"] = "Brightspear the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8866,["n"] = "Bronzebeard the Elder",["r"] = 1,["s"] = 1,},
	{ ["id"] = 8882,["n"] = "Cluster Launcher",["r"] = 55,["s"] = 3,},
	{ ["id"] = 8880,["n"] = "Cluster Rockets",["r"] = 45,["s"] = 3,},
	{ ["id"] = 8648,["n"] = "Darkcore the Elder",["r"] = 1,["s"] = 2,},
	{ ["id"] = 8677,["n"] = "Darkhorn the Elder",["r"] = 1,["s"] = 2,},
	{ ["id"] = 8683,["n"] = "Dawnstrider the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8684,["n"] = "Dreamseer the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8862,["n"] = "Elune's Candle",["r"] = 10,["s"] = 3,},
	{ ["id"] = 8727,["n"] = "Farwhisper the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8863,["n"] = "Festival Dumplings",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8864,["n"] = "Festive Lunar Dresses",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8865,["n"] = "Festive Lunar Pant Suits",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8878,["n"] = "Festive Recipes",["r"] = 50,["s"] = 3,},
	{ ["id"] = 8877,["n"] = "Firework Launcher",["r"] = 45,["s"] = 3,},
	{ ["id"] = 8653,["n"] = "Goldwell the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8652,["n"] = "Graveborn the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8679,["n"] = "Grimtotem the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8646,["n"] = "Hammershout the Elder",["r"] = 1,["s"] = 1,},
	{ ["id"] = 8686,["n"] = "High Mountain the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8643,["n"] = "Highpeak the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8651,["n"] = "Ironband the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8881,["n"] = "Large Cluster Rockets",["r"] = 55,["s"] = 3,},
	{ ["id"] = 8879,["n"] = "Large Rockets",["r"] = 35,["s"] = 3,},
	{ ["id"] = 8867,["n"] = "Lunar Fireworks",["l"] = 70,["r"] = 1,["s"] = 3,},
	{ ["id"] = 8722,["n"] = "Meadowrun the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8685,["n"] = "Mistwalker the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8714,["n"] = "Moonstrike the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8717,["n"] = "Moonwarden the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8619,["n"] = "Morndeep the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8724,["n"] = "Morningdew the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8723,["n"] = "Nightwind the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8645,["n"] = "Obsidian the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8654,["n"] = "Primestone the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8678,["n"] = "Proudhorn the Elder",["r"] = 1,["s"] = 2,},
	{ ["id"] = 8671,["n"] = "Ragetotem the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8725,["n"] = "Riversong the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8636,["n"] = "Rumblerock the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8670,["n"] = "Runetotem the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8642,["n"] = "Silvervein the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8675,["n"] = "Skychaser the Elder",["r"] = 1,["s"] = 1,},
	{ ["id"] = 8720,["n"] = "Skygleam the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8682,["n"] = "Skyseer the Elder",["r"] = 1,["s"] = 2,},
	{ ["id"] = 8876,["n"] = "Small Rockets",["r"] = 25,["s"] = 3,},
	{ ["id"] = 8650,["n"] = "Snowcrown the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8635,["n"] = "Splitrock the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8716,["n"] = "Starglade the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8713,["n"] = "Starsong the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8721,["n"] = "Starweave the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8644,["n"] = "Stonefort the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8672,["n"] = "Stonespire the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8649,["n"] = "Stormbrow the Elder",["r"] = 1,["s"] = 1,},
	{ ["id"] = 8872,["n"] = "The Lunar Festival",["l"] = 70,["r"] = 62,["s"] = 1,},
	{ ["id"] = 8875,["n"] = "The Lunar Festival",["l"] = 70,["r"] = 68,["s"] = 2,},
	{ ["id"] = 8874,["n"] = "The Lunar Festival",["l"] = 70,["r"] = 68,["s"] = 2,},
	{ ["id"] = 8873,["n"] = "The Lunar Festival",["l"] = 70,["r"] = 57,["s"] = 2,},
	{ ["id"] = 8871,["n"] = "The Lunar Festival",["l"] = 70,["r"] = 58,["s"] = 1,},
	{ ["id"] = 8870,["n"] = "The Lunar Festival",["l"] = 70,["r"] = 68,["s"] = 1,},
	{ ["id"] = 8681,["n"] = "Thunderhorn the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8883,["n"] = "Valadar Starsong",["l"] = 70,["r"] = 1,["s"] = 3,},
	{ ["id"] = 8676,["n"] = "Wildmane the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8688,["n"] = "Windrun the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8680,["n"] = "Windtotem the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8674,["n"] = "Winterhoof the Elder",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8868,["n"] = "Elune's Blessing",["r"] = 40,["s"] = 3,["t"] = 62,},
},
[-369] = {
	{ ["id"] = 11925,["n"] = "More Torch Catching",["r"] = 1,["s"] = 0,["d"] = 1,},
	{ ["id"] = 11924,["n"] = "More Torch Catching",["r"] = 1,["s"] = 0,["d"] = 1,},
	{ ["id"] = 11926,["n"] = "More Torch Tossing",["r"] = 1,["s"] = 0,["d"] = 1,},
	{ ["id"] = 11921,["n"] = "More Torch Tossing",["r"] = 1,["s"] = 0,["d"] = 1,},
	{ ["id"] = 11952,["n"] = "Striking Back",["l"] = 51,["r"] = 49,["s"] = 0,["d"] = 1,},
	{ ["id"] = 11917,["n"] = "Striking Back",["l"] = 22,["r"] = 17,["s"] = 0,["d"] = 1,},
	{ ["id"] = 11947,["n"] = "Striking Back",["l"] = 32,["r"] = 29,["s"] = 0,["d"] = 1,},
	{ ["id"] = 11948,["n"] = "Striking Back",["l"] = 43,["r"] = 39,["s"] = 0,["d"] = 1,},
	{ ["id"] = 11954,["n"] = "Striking Back",["l"] = 67,["r"] = 64,["s"] = 0,["d"] = 1,},
	{ ["id"] = 11953,["n"] = "Striking Back",["l"] = 60,["r"] = 56,["s"] = 0,["d"] = 1,},
	{ ["id"] = 11691,["n"] = "Summon Ahune",["l"] = 70,["r"] = 65,["s"] = 3,["d"] = 1,["t"] = 81,},
	{ ["id"] = 9365,["n"] = "A Thief's Reward",["r"] = 1,["s"] = 1,},
	{ ["id"] = 9339,["n"] = "A Thief's Reward",["r"] = 1,["s"] = 2,},
	{ ["id"] = 11696,["n"] = "Ahune is Here!",["l"] = 70,["r"] = 65,["s"] = 3,},
	{ ["id"] = 11891,["n"] = "An Innocent Disguise",["r"] = 16,["s"] = 3,},
	{ ["id"] = 11776,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11775,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11774,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11773,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11772,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11771,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11770,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11769,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11768,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11767,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11766,["n"] = "Desecrate this Fire!",["s"] = 1,},
	{ ["id"] = 11765,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11764,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11777,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11778,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11779,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11802,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11801,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11800,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11799,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11787,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11786,["n"] = "Desecrate this Fire!",["s"] = 1,},
	{ ["id"] = 11785,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11784,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11783,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11782,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11781,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11780,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11803,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11580,["n"] = "Desecrate this Fire!",["r"] = 14,["s"] = 0,},
	{ ["id"] = 11745,["n"] = "Desecrate this Fire!",["s"] = 2,},
	{ ["id"] = 11744,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11743,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11742,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11741,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11740,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11739,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11738,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11737,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11736,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11735,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11734,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11732,["n"] = "Desecrate this Fire!",["s"] = 1,},
	{ ["id"] = 11581,["n"] = "Desecrate this Fire!",["s"] = 2,},
	{ ["id"] = 11746,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11747,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11748,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11762,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11761,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11760,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11759,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11758,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11757,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11756,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11755,["n"] = "Desecrate this Fire!",["s"] = 1,},
	{ ["id"] = 11763,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11749,["n"] = "Desecrate this Fire!",["s"] = 2,},
	{ ["id"] = 11750,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11751,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11752,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11753,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11754,["n"] = "Desecrate this Fire!",["s"] = 0,},
	{ ["id"] = 11835,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11844,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11845,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11846,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11847,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11848,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11843,["n"] = "Honor the Flame",["s"] = 2,},
	{ ["id"] = 11842,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11841,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11840,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11838,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11837,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11836,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11839,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11850,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11863,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11862,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11861,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11860,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11859,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11858,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11857,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11856,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11855,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11854,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11853,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11852,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11851,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11849,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11583,["n"] = "Honor the Flame",["r"] = 1,["s"] = 0,},
	{ ["id"] = 11816,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11815,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11814,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11813,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11812,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11811,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11810,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11809,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11808,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11807,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11806,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11805,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11804,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11584,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11817,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11818,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11819,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11834,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11833,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11832,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11831,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11830,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11829,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11828,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11827,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11826,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11825,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11824,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11820,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11823,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11822,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11821,["n"] = "Honor the Flame",["s"] = 0,},
	{ ["id"] = 11966,["n"] = "Incense for the Festival Scorchlings",["r"] = 1,["s"] = 2,},
	{ ["id"] = 11964,["n"] = "Incense for the Summer Scorchlings",["r"] = 1,["s"] = 1,},
	{ ["id"] = 12012,["n"] = "Inform the Elder",["r"] = 16,["s"] = 3,},
	{ ["id"] = 11915,["n"] = "Playing with Fire",["r"] = 1,["s"] = 2,},
	{ ["id"] = 11882,["n"] = "Playing with Fire",["r"] = 1,["s"] = 1,},
	{ ["id"] = 11972,["n"] = "Shards of Ahune",["r"] = 65,["s"] = 3,},
	{ ["id"] = 9332,["n"] = "Stealing Darnassus's Flame",["r"] = 50,["s"] = 2,},
	{ ["id"] = 9331,["n"] = "Stealing Ironforge's Flame",["r"] = 50,["s"] = 2,},
	{ ["id"] = 9324,["n"] = "Stealing Orgrimmar's Flame",["r"] = 50,["s"] = 1,},
	{ ["id"] = 11935,["n"] = "Stealing Silvermoon's Flame",["r"] = 50,["s"] = 1,},
	{ ["id"] = 9330,["n"] = "Stealing Stormwind's Flame",["r"] = 50,["s"] = 2,},
	{ ["id"] = 11933,["n"] = "Stealing the Exodar's Flame",["r"] = 50,["s"] = 2,},
	{ ["id"] = 9326,["n"] = "Stealing the Undercity's Flame",["r"] = 50,["s"] = 1,},
	{ ["id"] = 9325,["n"] = "Stealing Thunder Bluff's Flame",["r"] = 50,["s"] = 1,},
	{ ["id"] = 11970,["n"] = "The Master of Summer Lore",["r"] = 1,["s"] = 1,},
	{ ["id"] = 11971,["n"] = "The Spinner of Summer Tales",["r"] = 1,["s"] = 2,},
	{ ["id"] = 11657,["n"] = "Torch Catching",["r"] = 1,["s"] = 0,},
	{ ["id"] = 11923,["n"] = "Torch Catching",["r"] = 1,["s"] = 0,},
	{ ["id"] = 11922,["n"] = "Torch Tossing",["r"] = 1,["s"] = 2,},
	{ ["id"] = 11731,["n"] = "Torch Tossing",["r"] = 1,["s"] = 1,},
	{ ["id"] = 11886,["n"] = "Unusual Activity",["r"] = 16,["s"] = 3,},
	{ ["id"] = 11955,["n"] = "Ahune, the Frost Lord",["l"] = 70,["r"] = 65,["s"] = 3,["t"] = 81,},
},
[-1006] = {
	{ ["id"] = 8860,["n"] = "New Year Celebrations!",["r"] = 7,["s"] = 1,},
	{ ["id"] = 8861,["n"] = "New Year Celebrations!",["s"] = 2,},
},
[-1001] = {
	{ ["id"] = 8744,["n"] = "A Carefully Wrapped Present",["r"] = 1,["s"] = 3,},
	{ ["id"] = 8803,["n"] = "A Festive Gift",["r"] = 10,["s"] = 3,},
	{ ["id"] = 8768,["n"] = "A Gaily Wrapped Present",["r"] = 20,["s"] = 3,},
	{ ["id"] = 8767,["n"] = "A Gently Shaken Gift",["r"] = 1,["s"] = 0,},
	{ ["id"] = 8788,["n"] = "A Gently Shaken Gift",["r"] = 1,["s"] = 0,},
	{ ["id"] = 6984,["n"] = "A Smokywood Pastures' Thank You!",["r"] = 30,["s"] = 0,},
	{ ["id"] = 7045,["n"] = "A Smokywood Pastures' Thank You!",["r"] = 30,["s"] = 0,},
	{ ["id"] = 8769,["n"] = "A Ticking Present",["r"] = 40,["s"] = 3,},
	{ ["id"] = 11528,["n"] = "A Winter Veil Gift",["r"] = 10,["s"] = 3,},
	{ ["id"] = 7021,["n"] = "Great-father Winter is Here!",["r"] = 31,["s"] = 0,},
	{ ["id"] = 7024,["n"] = "Great-father Winter is Here!",["s"] = 0,},
	{ ["id"] = 6961,["n"] = "Great-father Winter is Here!",["r"] = 10,["s"] = 2,},
	{ ["id"] = 7022,["n"] = "Greatfather Winter is Here!",["s"] = 1,},
	{ ["id"] = 7023,["n"] = "Greatfather Winter is Here!",["s"] = 1,},
	{ ["id"] = 8746,["n"] = "Metzen the Reindeer",["r"] = 40,["s"] = 2,},
	{ ["id"] = 8762,["n"] = "Metzen the Reindeer",["r"] = 40,["s"] = 1,},
	{ ["id"] = 6963,["n"] = "Stolen Winter Veil Treats",["r"] = 31,["s"] = 0,},
	{ ["id"] = 7042,["n"] = "Stolen Winter Veil Treats",["s"] = 0,},
	{ ["id"] = 7061,["n"] = "The Feast of Winter Veil",["r"] = 10,["s"] = 2,},
	{ ["id"] = 7063,["n"] = "The Feast of Winter Veil",["r"] = 10,["s"] = 1,},
	{ ["id"] = 8763,["n"] = "The Hero of the Day",["r"] = 40,["s"] = 0,},
	{ ["id"] = 8799,["n"] = "The Hero of the Day",["r"] = 40,["s"] = 0,},
	{ ["id"] = 6964,["n"] = "The Reason for the Season",["r"] = 19,["s"] = 2,},
	{ ["id"] = 7062,["n"] = "The Reason for the Season",["r"] = 60,["s"] = 1,},
	{ ["id"] = 6962,["n"] = "Treats for Great-father Winter",["r"] = 10,["s"] = 2,},
	{ ["id"] = 7025,["n"] = "Treats for Greatfather Winter",["r"] = 10,["s"] = 1,},
	{ ["id"] = 8827,["n"] = "Winter's Presents",["r"] = 1,["s"] = 1,},
	{ ["id"] = 8828,["n"] = "Winter's Presents",["r"] = 6,["s"] = 2,},
	{ ["id"] = 6983,["n"] = "You're a Mean One...",["r"] = 30,["s"] = 2,["t"] = 1,},
	{ ["id"] = 7043,["n"] = "You're a Mean One...",["r"] = 30,["s"] = 3,["t"] = 1,},
},
}